-- This file is auto-generated by sync_neovim_theme.sh
-- Do not edit it manually

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "generated"

local theme = {
  fg = "#FFFFFF",
  bg = "#111212",
  black = "#295252",
  red = "#FFF1CC",
  green = "#CCEAFF",
  yellow = "#CCECFF",
  blue = "#9AE6E6",
  magenta = "#9AC6E6",
  cyan = "#9ACAE6",
  white = "#FFF1CC",
  bright_black = "#578F8F",
  bright_red = "#F0DCAA",
  bright_green = "#AAD3F0",
  bright_yellow = "#AAD6F0",
  bright_blue = "#9AE6E6",
  bright_magenta = "#9AC6E6",
  bright_cyan = "#9ACAE6",
  bright_white = "#F0DCAA",
}

local function set_hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Set highlight groups
set_hl("Normal", { fg = theme.fg, bg = theme.bg })
set_hl("Visual", { bg = theme.bright_black })
set_hl("CursorLine", { bg = theme.bright_black })
set_hl("CursorColumn", { bg = theme.bright_black })
set_hl("LineNr", { fg = theme.bright_black })
set_hl("NonText", { fg = theme.bright_black })
set_hl("SpecialKey", { fg = theme.bright_black })
set_hl("Pmenu", { fg = theme.fg, bg = theme.bright_black })
set_hl("PmenuSel", { fg = theme.bright_black, bg = theme.fg })
set_hl("WildMenu", { fg = theme.bright_black, bg = theme.fg })
set_hl("TabLine", { fg = theme.white, bg = theme.bright_black })
set_hl("TabLineSel", { fg = theme.bright_black, bg = theme.fg })
set_hl("TabLineFill", { bg = theme.bright_black })

-- Syntax
set_hl("Comment", { fg = theme.bright_black, italic = true })
set_hl("Constant", { fg = theme.cyan })
set_hl("String", { fg = theme.green })
set_hl("Character", { fg = theme.green })
set_hl("Number", { fg = theme.yellow })
set_hl("Boolean", { fg = theme.yellow })
set_hl("Float", { fg = theme.yellow })
set_hl("Identifier", { fg = theme.blue })
set_hl("Function", { fg = theme.magenta })
set_hl("Statement", { fg = theme.red })
set_hl("Conditional", { fg = theme.red })
set_hl("Repeat", { fg = theme.red })
set_hl("Label", { fg = theme.red })
set_hl("Operator", { fg = theme.fg })
set_hl("Keyword", { fg = theme.red })
set_hl("Exception", { fg = theme.red })
set_hl("Type", { fg = theme.cyan })
set_hl("StorageClass", { fg = theme.cyan })
set_hl("Structure", { fg = theme.cyan })
set_hl("Typedef", { fg = theme.cyan })
set_hl("PreProc", { fg = theme.yellow })
set_hl("Include", { fg = theme.yellow })
set_hl("Define", { fg = theme.yellow })
set_hl("Macro", { fg = theme.yellow })
set_hl("PreCondit", { fg = theme.yellow })
set_hl("Title", { fg = theme.magenta, bold = true })
set_hl("Todo", { fg = theme.bg, bg = theme.yellow })
set_hl("Underlined", { underline = true })
set_hl("Error", { fg = theme.red, bg = theme.bright_black })
set_hl("ErrorMsg", { fg = theme.red, bg = theme.bright_black })
set_hl("WarningMsg", { fg = theme.yellow, bg = theme.bright_black })

-- Diffs
set_hl("DiffAdd", { bg = theme.green, fg = theme.bg })
set_hl("DiffChange", { bg = theme.yellow, fg = theme.bg })
set_hl("DiffDelete", { bg = theme.red, fg = theme.bg })
set_hl("DiffText", { bg = theme.blue, fg = theme.bg })

-- LSP
set_hl("LspDiagnosticsDefaultError", { fg = theme.red })
set_hl("LspDiagnosticsDefaultWarning", { fg = theme.yellow })
set_hl("LspDiagnosticsDefaultInformation", { fg = theme.blue })
set_hl("LspDiagnosticsDefaultHint", { fg = theme.cyan })

